---
tap_install:
  values: 
        profile: iterate
        ceip_policy_disclosed: true
        
        shared:
          ingress_domain: "akslab.tap.fynesy.com"
          #!ingress_issuer: "letsencrypt-production"

        image_policy_webhook:
          allow_unmatched_tags: true

        supply_chain: basic

        ootb_supply_chain_basic:
          registry: 
            server: "index.docker.io"
            repository: "fynesy" 
          gitops:
            ssh_secret: ""

        buildservice:
          kp_default_repository: "fynesy/buildservice"

        policy: 
          tuf_enabled: false

        contour:
          envoy:
            service:
              type: LoadBalancer 

        cnrs:
          domain_template: '{{.Name}}-{{.Namespace}}.{{.Domain}}'

        appliveview_connector:
          backend:
            sslDeactivated: true
            ingressEnabled: true
            host: appliveview.akslab.tap.fynesy.com