---
tap_install:
  values: 
        profile: build
        ceip_policy_disclosed: true
        
        shared:
          ingress_domain: "akslab-build.tap.fynesy.com"
          ingress_issuer: "letsencrypt-production"
          image_registry: 
            project_path: fynesy/build-service
            secret:
              name: user-registry-dockerconfig
              namespace: tap-install

        buildservice:
          kp_default_repository: fynesy/build-service
          kp_default_repository_secret:
            name: user-registry-dockerconfig
            namespace: tap-install

        supply_chain: basic

        ootb_supply_chain_basic: 
          registry:
            server: "index.docker.io"
            repository: "fynesy"
          gitops:
            ssh_secret: ""
          

        grype:
          namespace: "default"
          targetImagePullSecret: "tap-registry"
          metadataStore:
            url:
            caSecret:
              name: store-ca-cert
              importFromNamespace: metadata-store-secrets
        
        scanning:
          metadataStore:
            url: ""
        
        namespace_provisioner:
          controller: false
          gitops_install:
            ref: origin/main
            subPath: clusters/akslab-build/cluster-config/namespaces
            url: https://github.com/tfynes-pivotal/tap-gitops-mc
          additional_sources:
          - git:
              ref: origin/main
              subPath: clusters/akslab-build/cluster-config/namespaces/namespace-resources
              url: https://github.com/tfynes-pivotal/tap-gitops-mc
            path: _ytt_lib/namespace-resources


