apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: dependent-resources
  namespace: tanzu-sync
  annotations:
    kapp.k14s.io/change-rule.0: "upsert after upserting pkgi"
spec:
  serviceAccountName: sync-sa
  fetch:
    - git:
        ref: origin/main
        url: https://github.com/tfynes-pivotal/tap-gitops-mc
        subPath: clusters/akslab-view/cluster-config/dependent-resources
  template:
    - ytt: {}
  deploy:
    - kapp:
        rawOptions: ["--dangerous-allow-empty-list-of-resources=true"]
