---
tap_install:
  values: 
        profile: view
        ceip_policy_disclosed: true
        
        shared:
          ingress_domain: "akslab.tap.fynesy.com"
          ingress_issuer: "letsencrypt-production"

        contour:
          envoy:
            service:
              type: LoadBalancer 

        tap_gui:
          service_type: ClusterIP
          app_config:
            auth:
              allowGuestAccess: true
            catalog:
              locations:
                - type: url
                  target: http://github.com/tfynes-pivotal/tapblankcatalog/blob/main/catalog-info.yaml


        appliveview:
          ingressEnabled: true
